name: Publish Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd payment && npm ci
          cd ../atm && npm ci

      - name: Generate documentation
        run: |
          cd payment
          npx @compodoc/compodoc -p tsconfig.json -d ../docs/payment
          cd ../atm
          npx @compodoc/compodoc -p tsconfig.json -d ../docs/atm

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
